# ---------- Stage 1 : Build ----------
FROM node:22-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npm run build

# ---------- Stage 2 : Production ----------
FROM nginx:alpine

# Copy React build
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom Nginx config
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]